<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TipoFacturaSeeder extends Seeder
{
    public function run()
    {
        $tipos = [
            [
                'nombre'                        => 'Facturación Clientes A',
                'codigo'                        => 'estatal',
                'ruta_menu'                     => 'ventas/estatal',
                'tipo_venta_id'                 => 2,
                'restriccion'                   => 1,
                'max_descuento'                 => 50,
                'requiere_codigo_autorizacion'  => false,
                'requiere_codigo_exoneracion'   => false,
                'requiere_orden_compra'         => true,
                'aplica_isv'                    => true,
                'multiples_precios'             => false,
                'comision_fija'                 => null,
                'estado'                        => true,
                'orden'                         => 1,
                'created_at'                    => now(),
                'updated_at'                    => now(),
            ],
            [
                'nombre'                        => 'Facturación SR/Clientes A',
                'codigo'                        => 'sin_restriccion_gobierno',
                'ruta_menu'                     => 'ventas/sin/restriccion/gobierno',
                'tipo_venta_id'                 => 2,
                'restriccion'                   => 2,
                'max_descuento'                 => 35,
                'requiere_codigo_autorizacion'  => true,
                'requiere_codigo_exoneracion'   => false,
                'requiere_orden_compra'         => false,
                'aplica_isv'                    => true,
                'multiples_precios'             => true,
                'comision_fija'                 => null,
                'estado'                        => true,
                'orden'                         => 2,
                'created_at'                    => now(),
                'updated_at'                    => now(),
            ],
            [
                'nombre'                        => 'Facturación Clientes B',
                'codigo'                        => 'corporativa',
                'ruta_menu'                     => 'ventas/coporativo',
                'tipo_venta_id'                 => 1,
                'restriccion'                   => 1,
                'max_descuento'                 => 50,
                'requiere_codigo_autorizacion'  => false,
                'requiere_codigo_exoneracion'   => false,
                'requiere_orden_compra'         => true,
                'aplica_isv'                    => true,
                'multiples_precios'             => false,
                'comision_fija'                 => null,
                'estado'                        => true,
                'orden'                         => 3,
                'created_at'                    => now(),
                'updated_at'                    => now(),
            ],
            [
                'nombre'                        => 'Facturación SR/P Clientes B',
                'codigo'                        => 'sin_restriccion_precio',
                'ruta_menu'                     => 'ventas/sin/restriccion/precio',
                'tipo_venta_id'                 => 1,
                'restriccion'                   => 2,
                'max_descuento'                 => 35,
                'requiere_codigo_autorizacion'  => true,
                'requiere_codigo_exoneracion'   => false,
                'requiere_orden_compra'         => false,
                'aplica_isv'                    => true,
                'multiples_precios'             => true,
                'comision_fija'                 => null,
                'estado'                        => true,
                'orden'                         => 4,
                'created_at'                    => now(),
                'updated_at'                    => now(),
            ],
            [
                'nombre'                        => 'Facturación Exonerada',
                'codigo'                        => 'exoneradas',
                'ruta_menu'                     => 'ventas/exonerado/factura',
                'tipo_venta_id'                 => 3,
                'restriccion'                   => 1,
                'max_descuento'                 => 0,
                'requiere_codigo_autorizacion'  => false,
                'requiere_codigo_exoneracion'   => true,
                'requiere_orden_compra'         => false,
                'aplica_isv'                    => false,
                'multiples_precios'             => false,
                'comision_fija'                 => 0.50,
                'estado'                        => true,
                'orden'                         => 5,
                'created_at'                    => now(),
                'updated_at'                    => now(),
            ],
            [
                'nombre'                        => 'Cotización Clientes A',
                'codigo'                        => 'cotizacion_clientes_a',
                'ruta_menu'                     => 'proforma/cotizacion/2',
                'tipo_venta_id'                 => 2,
                'restriccion'                   => 1,
                'max_descuento'                 => 50,
                'requiere_codigo_autorizacion'  => false,
                'requiere_codigo_exoneracion'   => false,
                'requiere_orden_compra'         => false,
                'aplica_isv'                    => true,
                'multiples_precios'             => false,
                'comision_fija'                 => null,
                'estado'                        => true,
                'orden'                         => 6,
                'created_at'                    => now(),
                'updated_at'                    => now(),
            ],
        ];

        DB::table('tipo_factura')->insert($tipos);
    }
}
